[project]
name = "jokes-api"
version = "0.1.0"
description = "an API that will let you add and retrieve jokes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.7",
    "uvicorn>=0.34.3",
]
